using System.ComponentModel.DataAnnotations;

namespace PetShop.Models
{
  public class Cat
  {

    // This will be generated by the database
    public string Id { get; set; }

    [Required]
    [MinLength(3)]
    public string Name { get; set; }

    [Range(0, int.MaxValue)]
    public int? Age { get; set; }

    // ONLY REQUIRED WITH FAKEDB
    public Cat(string name, int? age)
    {
      Id = Guid.NewGuid().ToString();
      Name = name;
      Age = age;
    }



  }
}